### ISSUE TITLE
Create RStudio add-in for high level functions

### ISSUE THREAD

**Issue by jonmcalder** [lockedata/pRojects#12]
This might not be appropriate for the intended audience, but I figure if the primary goal is to prevent unnecessary typing and/or function calls in the process of setting up projects, packages etc, then maybe having these available from a drop-down might be useful. Could potentially even create a Shiny gadget using miniUI in order to facilitate input of the few required parameters for the high level functions.

**Comment by stephlocke** [comment]
I think this is a nifty idea Jon :)

**Comment by stephlocke** [comment]
@jonmcalder did a spectacular job - now just to maintain it!
