### ISSUE TITLE
Switch bookdown demo?

### ISSUE THREAD

**Issue by stephlocke** [lockedata/pRojects#29]
We currently use the full [bookdown-demo](https://github.com/rstudio/bookdown-demo) repo, but I'm considering the [nookdown-minimal](https://github.com/yihui/bookdown-minimal) one instead. It means a smaller install and less stuff someone might have to remove.

What do y'all think?

**Comment by jonmcalder** [comment]
Yes that seems like a good idea. As you say it makes sense to try and minimize fluff and keep the install small, especially given that this 'starting template' could later be configurable. I'm not yet sure what the full scope of #11 and #14 will be, but my thinking was that it could easily extend to this sort of config.

With that templating flexibility in place we should aim for 'small/neat/safe` defaults for config across the board.
