### ISSUE TITLE
Explore possibility for integration with or leveraging of ProjectTemplate

### ISSUE THREAD

**Issue by jonmcalder** [lockedata/pRojects#30]
[ProjectTemplate](https://github.com/johnmyleswhite/ProjectTemplate) is fairly well established. Obviously it takes things much further in terms of enforcing templates, project structure etc, so I suppose one could view `createAnalysisProject()` as a more lightweight alternative to it. 

Nevertheless, given that it has a fair amount of traction, I figure it's worth considering how we want to approach this functional overlap. Any thoughts on this?

**Comment by stephlocke** [comment]
Certainly seems to be a fair whack of overlap. pRojects works on an R package structure and is more in keeping with an Rstudio workflow which methodologically I find preferable. ProjectTemplate doesn't work the way I want to work but it's still a valid way to work.

I wonder if we could provide a function that wraps/calls out to ProjectTemplate and allow people to use it as a project type they could setup through pRojects?

**Comment by maelle** [comment]
> I wonder if we could provide a function that wraps/calls out to ProjectTemplate and allow people to use it as a project type they could setup through pRojects?

why? why not instead have an example of `createAnalysisProject` with `dirs` chosen to mimick what `ProjectTemplate` does?

**Comment by maelle** [comment]
I'm tempted to close this. Both packages have very different philosophies.

From a rather quick glance at `ProjectTemplates` docs here's what I think:

* it loads packages automatically. One can get that in a `pRoject` project by listing dependencies under `Depends`, and for that, one can run `usethis::use_package()` since `pRojects` uses the package structure.

* there seems to be a lot of work around caching. I think we'll solve this here via #39 

Anything I've missed? Any reason not to close this?

**Comment by maelle** [comment]
Poke @jonmcalder (do you use `ProjectTemplate` by the way?)

**Comment by jonmcalder** [comment]
No I don't use it - it just came to mind when I first saw `pRojects` since I had briefly looked into `ProjectTemplate` after hearing Hillary Parker refer to it (I think in one of the early episodes of NSSD). She also blogged about it a number of years ago - https://hilaryparker.com/2012/08/25/love-for-projecttemplate/

I agree that the philosophies are somewhat different and that's understandable since it seems `ProjectTemplate` originated long before the emergence of packages like `usethis` & `drake`.

Happy for you to close this.
