### ISSUE TITLE
Incorporating `goodpractice`

### ISSUE THREAD

**Issue by stephlocke** [lockedata/pRojects#35]
Should we add a pre-commit hook that will run good practice? It might make it so that if only if it passes it would commit - that's probably too onerous.

Perhaps just adding it to the pRojects Suggests?

**Comment by jonmcalder** [comment]
This could be worthwhile, but as you say possibly too onerous in many cases. And how much would really be gained by adding it to the pRojects Suggests though? Subtle suggestions probably aren't that likely to be noticed.

I think ideally we'd want to aim for something inbetween i.e. include some kind of specific prompt to actually encourage regular use of `gp()` - maybe this could be done semi-intelligently on some kind of interval, and/or set based on an environment variable or persistent package setting?

Wouldn't want to overcook things unnecessarily with loads of config, but I do think a pre-commit hook which runs it each time by default is probably a little aggressive.

**Comment by stephlocke** [comment]
I wonder if when we create a README it should default to some content about next steps maybe? Like "we added travis - here's the shield but you need to go turn travis CI on" kinda thing. that way we could include a line about running `gp()` and it might help folks use more of the features we bake into their projects.

**Comment by stephlocke** [comment]
Sounds like a plan!

**Comment by maelle** [comment]
cf #6 

So `goodpractice` output would be part of the "project health README"

**Comment by maelle** [comment]
And it wouldn't need to be run with the `rcmdcheck` stuff, since that would be included in the Travis build.

**Comment by maelle** [comment]
Closing in favor of #81
