### ISSUE TITLE
`styler` pre-commit hook

### ISSUE THREAD

**Issue by stephlocke** [lockedata/pRojects#42]
Auto-clean code before it get's committed perhaps?
http://styler.r-lib.org/

**Comment by rmflight** [comment]
That's a neat idea.

**Comment by maelle** [comment]
Or maybe a commit from Travis to a style branch, that one could PR into master?

**Comment by stephlocke** [comment]
I think that'd cause problems for people in terms of workflow because they'll forget those PRs when working locally and they'd end up causing merge conflicts. I know I forget my ciskip commits all the time and forget to pull before I push 🙊

**Comment by maelle** [comment]
If you have a `styler` pre-commit hook, you can't inspect the diff before, well, committing. 🤔

**Comment by maelle** [comment]
I'm not a regular Bash user but I think the whole `.git/hooks/pre-commit` text file could be:

```
#!/bin/bash
Rscript styler::style_package()
```

* Need to check `styler` is installed (probably including on Travis since Travis might make commits, thus the hook will be used).

* Need to check `Rscript` is available (not on the PATH by default on Windows)

**Comment by maelle** [comment]
The `Rscript` command could source a file.

**Comment by maelle** [comment]
Work in #94

* Better user experience than I thought to have such a hook! But will it slow things down to have `styler` run at each commit?

* Not sure whether saving the R script under hooks is ok.

* Still need to work on the compatibility with the `usethis::use_readme_rmd()` hook.

* Maybe add an argument to make it opt-out.

**Comment by maelle** [comment]
Now implemented, no way to opt out 😬
