### ISSUE TITLE
why the call to packrat:::augmentRprofile?

### ISSUE THREAD

**Issue by maelle** [lockedata/pRojects#47]
In https://github.com/lockedata/pRojects/blob/afa88b2923aa9e5858889f8b0c17e942d89f9fb6/R/createBasicProject.R#L32

The line after that calls `packrat::init` and it seems that it calls a function that calls `augmentRprofile` https://github.com/rstudio/packrat/blob/eaf443593fc48ca2a3ebc724e3a3297b6a6a9b69/R/packrat.R

But I've close to no `packrat` experience.

**Comment by stephlocke** [comment]
Great question @maelle! Unfortunately, it was two years ago and it looks like it's one of the first things I wrote in it! 🙊

Happy for you to see if things will work without it.
