### ISSUE TITLE
Spellcheck pre-commit hook

### ISSUE THREAD

**Issue by stephlocke** [lockedata/pRojects#6]
Add ability to include spellchecking via hunspell to projects

**Comment by maelle** [comment]
How would this look like given `devtools::spell_check` &co (https://github.com/ropensci/spelling ) false positives?

**Comment by maelle** [comment]
makes sense given that it is `lintr` recommended strategy

**Comment by maelle** [comment]
Probably using https://ropenscilabs.github.io/tic/reference/step_run_code.html

Not sure where the output should live, either on Travis log, or pushed to a project-checks branch whose README would only contain output from `devtools::spell_check()` and from `lintr`?

**Comment by maelle** [comment]
Closing in favour of #81
