### ISSUE TITLE
packrat in createTrainingProject

### ISSUE THREAD

**Issue by maelle** [lockedata/pRojects#61]
I do not understand

```r
  # Installation dir
  usePackrat <- !methods::hasArg("packrat")
  if (!usePackrat)
    usePackrat <- list(...)[["packrat"]]
  installDir <- ifelse(usePackrat, name, .libPaths())
```
yet, I need to have a proper look.

**Comment by stephlocke** [comment]
If someone doesn't provide the packrat arg then we can't retrieve the value through the various ellipses passthroughs so we have to use methods to check if the arg exists (if not usePAckrat = FALSE) and if it does exist, retrieve the value from the ellipses section and return its value (can be TRUE or FALSE)

**Comment by maelle** [comment]
I'll remove the ellipsis for now.
