### ISSUE TITLE
Remove the ellipsis when calling createBasicProject

### ISSUE THREAD

**Issue by maelle** [lockedata/pRojects#62]
and have the explicit arguments instead?

**Comment by stephlocke** [comment]
This means keeping a lot of stuff synced up - if usability gain is sufficiently high, I'd be happy for this to go ahead but it definitely has to be worth it.

**Comment by maelle** [comment]
I think it'd make the code easier to understand (cf #61 :wink:) so easier for contributors, and less risk of using an argument that doesn't exist, but I agree about maintenance... will think about it.

**Comment by maelle** [comment]
I'll be responsible for keeping stuff synced up @stephlocke 👼
