### ISSUE TITLE
Does checkpoint really fit in pRojects?

### ISSUE THREAD

**Issue by maelle** [lockedata/pRojects#65]
In https://cran.r-project.org/web/packages/checkpoint/vignettes/checkpoint.html I 👀 "Scans your project folder for all packages used. Specifically, it searches for all instances of library() and require() in your code."

At setup time, there's no packages used, only packages specified in DESCRIPTION, so `checkpoint` does nothing, e.g. if I run it in `createTrainingProject` I get

```
Scanning for packages used in this project
- Discovered 0 packages
No packages found to install
checkpoint process complete
```

and as far as I understood `pRojects` philosophy, what we'd want is a package that'd get dependencies from DESCRIPTION (and help setup DESCRIPTION, but not bypass that step)? 🤔

**Comment by stephlocke** [comment]
Folks can regularly re-snapshot to re-detect packages in use. This is lighter than than the packrat implementation.

**Comment by stephlocke** [comment]
Most folks won't know what packages they'll use at project creation time so I'm happy with it detecting 0 packages to begin with

**Comment by maelle** [comment]
Am still having trouble getting it to work. 🤔
