### ISSUE TITLE
Nord for internal functions?

### ISSUE THREAD

**Issue by maelle** [lockedata/pRojects#79]

**Comment by maelle** [comment]
I am at least strongly in favour of _not_ having them in the reference of the `pkgdown` website.

Any opinion on this @stephlocke ? _I_ prefer not seeing internal functions in the package docs, but this is your package :wink:

**Comment by stephlocke** [comment]
I thought you were referring to a scandinavian person 😂 Happy for internal functions not to show on pkgdown

**Comment by maelle** [comment]
And not in the local docs either?

For the record I am also puzzled by my own issue title! "What's a nord? Oh I meant No Rd" :joy:
