### ISSUE TITLE
covrpage does not deploy anymore

### ISSUE THREAD

**Issue by maelle** [lockedata/pRojects#97]
https://travis-ci.org/lockedata/pRojects/builds/468949421#L1330

Any tip @yonicd?

**Comment by yonicd** [comment]
Where is covrpage installed in tic.R?

**Comment by yonicd** [comment]
Pushed patch to covrpage, you can try again.

**Comment by maelle** [comment]
Build running now 🍿

**Comment by maelle** [comment]
works now, thanks!
